EstacionaService/Models/ClienteModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EstacionaService.Models
{
  public class ClienteModel
  {
    public string Placa { get; set; }
    public string ID { get; set; }
    public string Descricao { get; set; }
    public string TipoVeiculo { get; set; }
    public string TempoGasto { get; set; }
    public DateTime? Entrada { get; set; }
    public DateTime? Saida { get; set; }
    public bool? Situacao { get; set; }
    public decimal? ValorAPagar { get; set; }

  }



}

EstacionaService/Models/ErrorViewModel.cs
using System;

namespace EstacionaService.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EstacionaService/Models/MensalistaPFModel.cs
using System;
namespace EstacionaService.Models
{
  public class MensalistaPFModel
  {

    public string CPF { get; set; }
    public string Nome { get; set; }
    public string Placa { get; set; }
    public string TipoVeiculo { get; set; }
    public string Descricao { get; set; }
    public DateTime DataEntrada { get; set; }
    public int Plano { get; set; }
    public decimal Valor { get; set; }
    public bool Situacao { get; set; }
  }
}

EstacionaService/Controllers/ClientesController.cs
using EstacionaService.Service;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EstacionaService.Controllers
{

  public class ClientesController : ControllerBase
  {
    private ClientesService _service;
    public ClientesController()
    {
      _service = new ClientesService();
    }

    [HttpPost("api/InserirCliente")]
    public IActionResult InserirCliente([FromBody] Models.ClienteModel cliente)
    {
      try
      {

        cliente.Saida = Convert.ToDateTime("00:00");
        _service.InserirCliente(cliente);

        return StatusCode(200, "Sucesso ao inserir");
      }
      catch (InvalidOperationException)
      {
        return StatusCode(400, "Erro ao inserir");
      }
      catch (Exception ex)
      {
        return StatusCode(500, "Erro ao conectar ao servidor: " + ex.Message);
      }
    }

    [HttpGet("api/ListarClientes")]
    public IActionResult ListarClientes()
    {
      try
      {
        var listaClientes = _service.ListarClientes();

        var lista = listaClientes.Select(x => new
        {
          x.ID,
          x.Descricao,
          x.Placa,
          x.TipoVeiculo,
          x.Entrada

        }).ToList();

        return StatusCode(200, lista);
      }
      catch (Exception)
      {
        return StatusCode(500, "Erro ao realizar a busca");
      }
    }
    [HttpPut("api/FecharValor/{id}")]
    public IActionResult FechamentoCliente(string id)
    {
      try
      {
        var clienteFechamento = _service.FechamentoCliente(id);
        return StatusCode(200, clienteFechamento);
      }
      catch (Exception EX)
      {
        return StatusCode(500, "Erro ao realizar o fechamento: " + EX.Message);
      }
    }

    [HttpPut("api/Pagamento")]
    public IActionResult Pagamento(decimal valorPago, decimal valorAReceber, string id)
    {
      try
      {
        var pagamento = _service.Pagamento(valorPago, valorAReceber, id);
        return StatusCode(200, pagamento);
      }
      catch (Exception EX)
      {
        return StatusCode(500, "Erro ao realizar o pagamento: " + EX.Message);
      }
    }
  }
}

EstacionaService/Controllers/HomeController.cs
using EstacionaService.Models;
using EstacionaService.RegrasDeNegocio;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EstacionaService.Controllers
{
  public class HomeController : Controller
  {
    private readonly ILogger<HomeController> _logger;
    private Service.ClientesService _service;

    public HomeController(ILogger<HomeController> logger)
    {
      _logger = logger;
      _service = new Service.ClientesService();
    }

    public IActionResult Index()
    {
      return View();
    }

    public IActionResult ListarClientesAtivos()
    {
      var clientes = _service.ListarClientes();

      return StatusCode(200, clientes);
    }

    [HttpPost]
    public IActionResult InserirCliente([FromBody] ClienteModel cliente)
    {
      try
      {
        Validacao.ValidarEntradaVeiculo(cliente);
        _service.InserirCliente(cliente);

        return StatusCode(200);
      }
      catch (InvalidOperationException ex)
      {
        return StatusCode(400, ex.Message);
      }
    }

    [HttpPut("/")]
    public IActionResult FechamentoCliente([FromBody] string id)
    {
      var clienteFechado = _service.FechamentoCliente(id);

      return StatusCode(200, clienteFechado);
    }

    public IActionResult Privacy()
    {
      return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
      return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
  }
}

EstacionaService/Controllers/MensalistaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EstacionaService.Controllers
{
    public class MensalistaController : Controller
    {
        private readonly ILogger<MensalistaController> _logger;
        private Service.MensalistaService _service;

        public MensalistaController(ILogger<MensalistaController> logger)
        {
            _logger = logger;
            _service = new Service.MensalistaService();
        }

        public IActionResult Index()
        {
            return View();
        }


        public IActionResult ListarMensalistasPF()
        {
            var data = _service.ListarMensalistasPF().Select(x => new
            {
                cpf = "<p>" + x.Cpf + "</p>",
                nome = "<p>" + x.Nome + "</p>",
                placa = "<p>" + x.Placa + "</p>",
                tipoVeiculo = "<p>" + x.TipoVeiculo + "</p>",
                descricao = "<p>" + x.Descricao + "</p>",
                situacao = x.Situacao == false ? "<p>Inativo</p>" : "<p>Ativo</p>",
                action = $"<a type=\"button\" class=\"btn btn-warning btn-sm\">Teste</a>"
            }).ToList();

            return StatusCode(200, new { data = data });
        }


    }
}

EstacionaService/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Dashboard";
}
<form id="entradaVeiculos">
    <div class="row" style="display: flex;">
        <div class="col-2">

            <input class="form-control" type="text" id="placaEntradaPatio" placeholder="Placa veículo">
        </div>
        <div class="col-3">

            <input class="form-control" list="datalistOptions" id="tipoEntradaPatio" placeholder="Digite o tipo">
            <datalist id="datalistOptions">
                <option value="Moto"></option>
                <option value="Carro"></option>
                <option value="Caminhão"></option>
            </datalist>
        </div>
        <div class="col-4">

            <input class="form-control" type="text" id="descricaoEntradaPatio" placeholder="Descrição">
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-primary">Entrar com Veiculo</button>
        </div>
    </div>
</form>
<div class="row mt-3">
    <h4>Veículos ativos no pátio</h4>
</div>

<div class="row " id="cardContainer" style="display: flex; flex-wrap: wrap; justify-content:flex-start">
</div>




@section Scripts{
    <script>

        var urlListaClientes = '@Url.Action("ListarClientesAtivos", "Home")';
        var urlCadastrarVeiculo = '@Url.Action("InserirCliente","Home")';
        var urlFecharCliente = '@Url.Action("FechamentoCliente", "Home")';
    </script>

    <script type="text/javascript" src="/js/js-countdown/jquery.plugin.js"></script>
    <script type="text/javascript" src="js/js-countdown/jquery.countdown.js"></script>
    <script type="text/javascript" src="/js/paginaPrincipal.js"></script>


}

EstacionaService/Views/Mensalista/Index.cshtml
@{
    ViewData["Title"] = "Dashboard - Mensalista";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.8.8/semantic.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/dataTables.semanticui.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.2.3/css/buttons.semanticui.min.css">






<div class="container-fluid">
    
    <h1>Mensalistas</h1>

    <div class="table-responsive-md">
        <table id="mensalistas" class="ui  very basic table  ">
            <thead>
            <th class="col-md-2 tableTitle">CPF/CNPJ</th>
            <th class="col-md-4 tableTitle">Nome</th>
            <th class="cold-md-1 tableTitle">Placa</th>
            <th class="col-md-1 tableTitle">Veículo</th>
            <th class="col-md-2 tableTitle">Descrição</th>
            <th class="col-md-1 tableTitle">Situação</th>
            <th class="col-md-1 tableTitle"></th>
            </thead>
        </table>
    </div>
</div>

<style>
    .dataTables_filter input {
      color: white;
      border-radius: 40px 10px !important;
    }
</style>

@section Scripts{
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.8.8/semantic.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.semanticui.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.semanticui.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.colVis.min.js"></script>


    <script>
        var urlDataTable = '@Url.Action("ListarMensalistasPF", "Mensalista")';



    </script>

    <script type="text/javascript" src="/js/mensalistas.js"></script>
}

EstacionaService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>@ViewData["Title"] - EstacionaService</title>
    <!-- Favicon icon -->
    <link rel="icon" type="~/image/png" sizes="16x16" href="images/favicon.png">
    <!-- Custom Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />







</head>

<body>
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>

    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        <div class="nav-header">
            <div class="brand-logo logoSiteTexto">
                <a href="/">
                    <p class="logo-abbr logotexto">ES </p>
                    <span class="logo-compact"></span>
                    <p class="brand-title logotexto text-nowrap">EstacionaService</p>
                </a>
            </div>
        </div>
        <!--**********************************
            Nav header end
        ***********************************-->
        <!--**********************************
            Header start
        ***********************************-->
        <div class="header">
            <div class="header-content clearfix">

                <div class="nav-control">
                    <div class="hamburger">
                        <span class="toggle-icon"><i class="icon-menu"></i></span>
                    </div>
                </div>

            </div>
        </div>
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->
        <!--**********************************
            Sidebar start
        ***********************************-->
        <div class="nk-sidebar">
            <div class="nk-nav-scroll">
                <ul class="metismenu" id="menu">
                    <li class="nav-label">Dashboard</li>
                    <li>
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="icon-speedometer menu-icon"></i><span class="nav-text">Dashboard</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="/">Pátio</a></li>
                            <!-- <li><a href="./index-2.html">Home 2</a></li> -->
                        </ul>
                    </li>

                    <li>
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="icon-user menu-icon"></i><span class="nav-text ">Mensalistas</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="/Mensalista/Index">Pessoa Física</a></li>
                            <li><a href="/Mensalista/Index">Pessoa Jurídica</a></li>

                        </ul>
                    </li>



                    <li class="nav-label">Usuário</li>
                    <li>
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="icon-user menu-icon"></i><span class="nav-text ">Usuário</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="./page-login.html">Login</a></li>
                            <li><a href="./page-register.html">Register</a></li>
                            <li><a href="./page-lock.html">Lock Screen</a></li>
                            <li>
                                <a class="has-arrow" href="javascript:void()" aria-expanded="false">Error</a>
                                <ul aria-expanded="false">
                                    <li><a href="./page-error-404.html">Error 404</a></li>
                                    <li><a href="./page-error-403.html">Error 403</a></li>
                                    <li><a href="./page-error-400.html">Error 400</a></li>
                                    <li><a href="./page-error-500.html">Error 500</a></li>
                                    <li><a href="./page-error-503.html">Error 503</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>

        <div class="content-body">
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>

        <div class="footer navbar-fixed-bottom">
            <div class="copyright">
                <p>Copyright &copy; Desenvolvido por <a href="#">Lacir Junior</a> 2022</p>
            </div>
        </div>

    </div>
    <style>
        .logoSiteTexto{
            padding: 0 !important;
            display: flex;
            justify-content: center;
            align-items: center;
        }


    </style>
    <script src="~/plugins/common/common.min.js"></script>
    <script src="~/js/custom.min.js"></script>
    <script src="~/js/settings.js"></script>
    <script src="~/js/gleek.js"></script>
    <script src="~/js/styleSwitcher.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>


    @RenderSection("Scripts", required: true)

</body>

</html>